apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-bzp6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-obro-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-bzp6@sha256:b70e1388f78f10e8a0c05d2730e059473dae0bf749e343a4b22c49a45d6b36ed
        name: my-python
        resources: {}
status: {}
